# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: ["stable", "nightly"]
        lua-version: ["5.1", "5.4"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: ${{ matrix['lua-version'] }}

      - name: Set up Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix['neovim-version'] }}

      - name: Install Dependencies
        run: |
          nvim --headless +'!mkdir -p ~/.local/share/nvim/site/pack/plugins/start' +qall
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim \
            ~/.local/share/nvim/site/pack/plugins/start/plenary.nvim

      - name: Run Tests
        run: |
          nvim --headless \
            -u tests/minimal_init.vim \
            -c "PlenaryBustedDirectory tests/ { minimal_init = './tests/minimal_init.vim' }"
